# Generated by Django 6.0.6 on 2026-06-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True, help_text='Адрес или пункт выдачи СДЭК')),
                ('sdek_pvz_code', models.CharField(blank=True, help_text='Код ПВЗ СДЭК', max_length=50, null=True)),
                ('status', models.CharField(choices=[('new', 'Новый'), ('pending', 'Ожидает проверки'), ('confirmed', 'Подтвержден'), ('shipped', 'Отправлен'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='new', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_one_click', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
